import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '../components/AboutMe'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Project from '../components/Project'
import data from '../data/Personal.js';
// import BlogCard from '../components/BlogCard/BlogCard'
// import { GraphQLClient } from 'graphql-request'
// import QUEARYALLBLOG from "../Middleware/get-blog-api";
// import BlogLayout from '../Layouts/BlogLayout'
// import HomeLayout from '../Layouts/HomeLayout'
import Contact from '../components/Contact'
import Technologies from '../components/Technologies'
import WorkExperience from '../components/WorkExperience'
import CourseTaken from '../components/CourseTaken'
import Footer from '../components/Footer'

// const graphcms = new GraphQLClient("https://api-ap-northeast-1.graphcms.com/v2/cl4il4eos41je01z69eikf0ly/master");

// export async function getStaticProps() {
//   const {posts} = await graphcms.request(QUEARYALLBLOG);
//   return {
//       props: {
//           posts
//       },
//       revalidate: 10,
//   }
// }

const Home: NextPage = ({ posts }: any) => {
  return (
    <>
      <Head>
        <title>Daffa Aditya Rahman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container max-w-[1200px]'>
        <Navbar />
        <Hero />
        <AboutMe />
        <Project data={data}/>
        <Technologies/>
        <WorkExperience/>
        <CourseTaken/>
        <Contact/>
        <Footer />
        
        {/* <BlogLayout>
          {posts.slice(0,3).map((post: any) => (
            <div className="" key={post.title}>
                <BlogCard 
                    title={post.title}
                    key={post.id}
                    datePublished={post.datePublished}
                    slug={post.slug}
                    timeRead={post.timeRead}
                    description={post.description}
                />
            </div>
          ))}
        </BlogLayout> */}
      </div>
    </>
  )
}


export default Home;
