import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { compile } from '@mdx-js/mdx';
import rehypePrism from 'rehype-prism-plus';

const postsDirectory = path.join(process.cwd(), 'posts');
const targetDirectory = path.join(process.cwd(), 'pages', 'blog', 'post');

async function syncPosts() {
  console.log('🔄 Syncing blog posts to Pure TSX pages...');

  if (!fs.existsSync(targetDirectory)) {
    fs.mkdirSync(targetDirectory, { recursive: true });
  }

  const fileNames = fs.readdirSync(postsDirectory).filter(file => file.endsWith('.md'));

  for (const fileName of fileNames) {
    const id = fileName.replace(/\.md$/, '');
    const fullPath = path.join(postsDirectory, fileName);
    const fileContents = fs.readFileSync(fullPath, 'utf8');

    const { data, content } = matter(fileContents);
    const meta = {
      id,
      ...data,
      date: data.date ? new Date(data.date).toISOString() : null,
    };

    console.log(`Processing: ${id}`);
    
    // Compile MDX to JSX code
    const compiled = await compile(content, {
        jsx: true, // Output JSX, not JS with _jsx calls
        rehypePlugins: [rehypePrism],
        // providerImportSource: '@mdx-js/react', // optional
    });

    let code = String(compiled);

    // The compiled code has "export default function MDXContent...".
    // We want to rename it and keep it local.
    // Replace "export default function MDXContent" with "function MDXContent"
    code = code.replace(/export\s+default\s+function\s+MDXContent/, 'function MDXContent');

    const tsxContent = `
/* eslint-disable */
// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
import React from 'react';
import PostLayout, { components } from './layout';

${code}

const meta = ${JSON.stringify(meta)};

export default function Post() {
  return (
    <PostLayout meta={meta}>
      <MDXContent components={components} />
    </PostLayout>
  );
}
`;

    const targetPath = path.join(targetDirectory, `${id}.tsx`);
    fs.writeFileSync(targetPath, tsxContent);
    console.log(`✅ Generated: pages/blog/post/${id}.tsx`);
  }

  console.log('✨ All posts synced!');
}

syncPosts().catch(console.error);
